version: '3.8'

services:
  crypto-volatility-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=sqlite:///data/crypto_volatility.db
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./reports:/app/reports
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Future: Add PostgreSQL database
  # postgres:
  #   image: postgres:13
  #   environment:
  #     POSTGRES_DB: crypto_volatility
  #     POSTGRES_USER: crypto_user
  #     POSTGRES_PASSWORD: crypto_password
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"
  #   restart: unless-stopped

  # Future: Add Redis for caching
  # redis:
  #   image: redis:6-alpine
  #   ports:
  #     - "6379:6379"
  #   restart: unless-stopped

# volumes:
#   postgres_data:
